---
all:
  hosts:
    192.168.1.180:
      hostname: kcl-pi-0
    192.168.1.181:
      hostname: kcl-pi-0

  vars:
    ansible_user: alarm
    ansible_become_method: su
    ansible_become_password: "{{ lookup('env', 'ANSIBLE_ROOT_PASSWORD')}}"
