---
all:
  hosts:
    r-0:
    r-1:
    r-2:
    r-3:
    r-4:
    r-5:

  children:
    alpine:
      hosts:
        r-0:
        r-1:
        r-2:
        r-3:
        r-4:
        r-5:
    
  vars:
    ansible_user: dvitali
    ansible_become_method: sudo
    # ansible_become_password: "{{ lookup('env', 'ANSIBLE_SUDO_PASSWORD')}}"
